### ISSUE TITLE
Using a newline causes the loading screen to go black.

### ISSUE THREAD

**Issue by PikaDude** [modmuss50/LoadingTips#4]
Trying to use \n or \r in a tip to try and create a newline causes the loading screen to not render and produce the following error:
```
[18:03:21] [Thread-4/ERROR]: Splash thread Exception
java.lang.IllegalArgumentException: null
	at net.minecraftforge.fml.client.SplashProgress$SplashFontRenderer.bindTexture(SplashProgress.java:903) ~[SplashProgress$SplashFontRenderer.class:?]
	at net.minecraft.client.gui.FontRenderer.loadGlyphTexture(FontRenderer.java:356) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.renderUnicodeChar(FontRenderer.java:373) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.renderChar(FontRenderer.java:306) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.renderStringAtPos(FontRenderer.java:590) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.renderString(FontRenderer.java:713) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.drawString(FontRenderer.java:443) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.drawString(FontRenderer.java:413) ~[bip.class:?]
	at me.modmuss50.loadingtips.LoadingTipsHooks.drawString(LoadingTipsHooks.java:85) ~[LoadingTipsHooks.class:?]
	at me.modmuss50.loadingtips.LoadingTipsHooks.draw(LoadingTipsHooks.java:54) ~[LoadingTipsHooks.class:?]
	at net.minecraftforge.fml.client.SplashProgress$2.run(SplashProgress.java:302) ~[SplashProgress$2.class:?]
```
I'm trying to add a newline so I can get the tip text to wrap since there doesn't seem to be a way to allow that and long tips just trail off of the screen. A fix or workaround would be appreciated. Thanks.

**Comment by matteo335** [comment]
For me, it's a screen freeze.
